server {
    server_name jumpshiny.genenetwork.org;

    access_log /var/log/nginx/jumpshiny-access.log;
    error_log /var/log/nginx/jumpshiny-error.log;
        
    location / {
        proxy_pass http://127.0.0.1:3978/;
        proxy_redirect / $scheme://$http_host/;

        proxy_set_header   Host             $host;
        proxy_set_header   X-Real-IP        $remote_addr;
        proxy_set_header   X-Forwarded-For  $proxy_add_x_forwarded_for;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        
        proxy_read_timeout 60m;

        proxy_buffering off;

    }   
}       
